###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

no_raxa-mailhog:
  image: phpdockerio/mailhog:latest
  container_name: no_raxa-mailhog
  ports:
    - "8125:8025"

no_raxa-mysql:
  image: mysql
  container_name: no_raxa-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=no_raxa
    - MYSQL_USER=no_raxa
    - MYSQL_PASSWORD=no_raxa
  ports:
    - "8106:3306"
  volumes:
    - ../mysql:/var/lib/mysql

no_raxa-mysql-test:
  image: mysql
  container_name: no_raxa-mysql-test
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=no_raxa
    - MYSQL_USER=no_raxa
    - MYSQL_PASSWORD=no_raxa
  ports:
    - "8107:3306"
  volumes:
    - ../mysql:/var/lib/mysql_test

no_raxa-nginx:
  image: phpdockerio/nginx:latest
  container_name: no_raxa-nginx
  volumes:
      - ../cakephp:/var/www/no_raxa
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8180:80"
  links:
   - no_raxa-php-fpm

no_raxa-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: no_raxa-php-fpm
  volumes:
    - ../cakephp:/var/www/no_raxa
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - no_raxa-mailhog
    - no_raxa-mysql
    - no_raxa-mysql-test
